#!/bin/sh

echo "Checking commit format..."

LOCAL_commitMsg=$(cat "$1")
MATCHED_COMMIT=$(echo "$LOCAL_commitMsg" | sed -E 's/[0-9]{1,}.*/\1/')
if [ -z "$MATCHED_COMMIT" ]; then
    echo "[ FAIL ] Invalid commit format"
    exit 1
fi
echo "[  OK  ] Commit format is normal"
